import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/dist/client/link';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { useUser } from '@auth0/nextjs-auth0'
import dataGames from '../data/games.json'
import { nanoid } from 'nanoid';


export default function Home() {

  const { user, error, isLoading } = useUser();

  const games = dataGames.map( game => {
    return(
      <Link href={game.href} key={nanoid()}>
          <a className='game-link'>
            <h3>{game.title}</h3>
            <img src={game.img} width={100} height={100}/>
            <button>Play</button>
          </a>
      </Link>
    )
  })

  return (
    <div className='home'>
      <Head>
        <title>FunLearn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@500&family=Kumbh+Sans:wght@500&display=swap"  /*rel="stylesheet"*/ />
      </Head>

      <Header />

      <div className='home__first-page'>
        <h1>
          <span style={{color:'#FF0000'}}>F</span>
          <span style={{color:'#FF00F6'}}>u</span>
          <span style={{color:'#00AA00'}}>n</span>
          <span style={{color:'#F99D07'}}>L</span>
          <span style={{color:'#FF0066'}}>e</span>
          <span style={{color:'#0000FF'}}>a</span>
          <span style={{color:'#37B6F6'}}>r</span>
          <span style={{color:'#882FF6'}}>n</span>
        </h1>
        <h3>A place where you can play and learn</h3>
      </div>
      <div className='home__info'>


      {user ? <>
        <h2>Welcome {user.name}!</h2>
        <h2>Games</h2>
        <div className='games-container'>
          {games}
        </div>
      </> : <>

      <h2>Why choose FunLearn?</h2>
      <div className='home__first-line'>
          <div>
            <Image src='/images/lightbulb.png' width={100} height={100} className='animation'/>
            <h3>Educational platform</h3>
          </div>
          <div>
            <Image src='/images/book2.png' width={100} height={100} className='animation'/>
            <h3>Accesible for everyone</h3>
          </div>
          <div>
            <Image src='/images/book.png' width={100} height={100} className='animation'/>
            <h3>Free learning</h3>
          </div>
          <div>
            <Image src='/images/engineering.png' width={100} height={100} className='animation'/>
            <h3>No ads</h3>
          </div>
      </div>
      

      <h2>A helpful tool for teachers</h2>
      <ul>
        <li>Increase the confidence, autonomy and determination of your students</li>
        <li>Motivate your students with FunLearn</li>
        <li>Have full control over the progress of your students</li>
        <li>Easily offer personalized learning</li>
        <li>Take advantage of an educational platform aligned with your academic program</li>
      </ul>

      <h2>An essential help for parents</h2>
      <ul>
        <li>Make math enjoyable and interesting</li>
        <li>Nurture your children’s confidence in math</li>
        <li>Follow their progress in real time</li>
        <li>Take advantage of educational games aligned with math curriculums</li>
        <li>Help your children reach their full potential autonomously</li>
      </ul>
      </> }
        </div>
      <Footer />
    </div>
  )
}
